- name: Backend Setup 
  hosts: all
  become: yes
  tasks:
    - name: Install NodeJS
      ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash
    - name: Install NodeJS
      ansible.builtin.dnf:
        name: nodejs
    - name: Copy Backend Serivice File
      ansible.builtin.copy:
        src: backend.service
        dest: /etc/systemd/system/backend.service
    - name: Add Application User
      ansible.builtin.user:
        name: expense
    - name: Cleanup Old Content
      ansible.builtin.file:
        path: /app
        state: absent
    - name: Create app directory
      ansible.builtin.file:
        path: /app
        state: absent
    - name: Download backend code and extract it
      ansible.builtin.unarchive:
        src: https://expense-artifacts.s3.amazonaws.com/backend.zip
        dest: /usr/share/nginx/html
        remote_src: yes
    - name: Install NodeJS dependencies
      ansible.builtin.shell: npm install
      args:
        chdir: /app
    - name: Install My Sql client
      ansible.builtin.dnf:
        name: mysql
    - name: Load Schema  
      ansible.builtin.shell: mysql -h mysql.sddevops18.online -uroot -pExpenseApp@1 < /app/schema/backend.sql
    - name: Starting backend service
      ansible.builtin.systemd:
        name: backend
        state: restarted
        enabled: yes
      