- name: Verify NodeJS
  ansible.builtin.shell: type npm
  register: npm
  
#- name: Read npm
# ansible.buildin.debug:
#  msg: "{{npm}}"
  
- name: Install NodeJS
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash
  when: npm.rc != 0
  
- name: Install NodeJS
  ansible.builtin.dnf:
    name: nodejs
  when: npm.rc != 0
        
- name: Copy Backend Serivice File
  ansible.builtin.copy:
    src: backend.service
    dest: /etc/systemd/system/backend.service
    
- name: Add Application User
  ansible.builtin.user:
    name: expense
  
- name : Include App Pre-Requisites
  ansible.buildin.import_role:
    name: common
    tasks_from: app_prereq  
    
- name: Install NodeJS dependencies
  ansible.builtin.shell: npm install
  args:
    chdir: /app
    
- name: Install My Sql client
  ansible.builtin.dnf:
    name: mysql
    
- name: Load Schema  
  ansible.builtin.shell: mysql -h mysql.sddevops18.online -uroot -pExpenseApp@1 < /app/schema/backend.sql
  
- name: Starting backend service
  ansible.builtin.systemd:
    name: backend
    state: restarted
    enabled: yes
